version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 750
  method-complexity:
    enabled: true
    config:
      threshold: 6
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 6
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 100
  identical-code:
    enabled: true
    config:
      threshold: 100
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .html
        - .js
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - HERE BE DRAGONS
      - Here Be Dragons
  grep:
    enabled: true
    config:
      patterns:
        bad-merge:
          pattern: <<<<<<<|=======|>>>>>>>
          annotation: "Bad merge"
          severity: critical
          categories: ["Bug Risk", "Performance"]
          content: >
            Bad merge detected by one or more of the following strings of the form: "<<<<<<< Updated upstream", "=======", ">>>>>>> Stashed changes". In all likelihood, this will result in syntax errors when attempting to run your application.
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
  - ".*"
  - bower_components/
  - build/
  - dist/
  - src/
  - "**/*-polyfill.js"
  - node_modules/
  - "**/reports/**/*"
  - "**/test/**/*"
