version: ~> 1.0

# This Travis CI configuration makes use of imports (https://docs.travis-ci.com/user/build-config-imports/) to commonize and simplify build configuration. Utilizes shallow merge, allowing overwrites for most root level sections, and deep merge for notifications.
import:
  - source: fs-webdev/fs-common-build-scripts:travis/base.yml@v2
    mode: merge
  - source: fs-webdev/fs-common-build-scripts:travis/sauce.yml@v2
    mode: merge
  - source: fs-webdev/fs-common-build-scripts:travis/notifications.yml@v2
    mode: deep_merge
  - source: fs-webdev/fs-common-build-scripts:travis/notifications/tw-gold.yml@v2
    mode: deep_merge
  - source: fs-webdev/fs-common-build-scripts:travis/before.yml@v2
    mode: merge
  - source: fs-webdev/fs-common-build-scripts:travis/install_with_bower.yml@v2
    mode: deep_merge_prepend
  - source: fs-webdev/fs-common-build-scripts:travis/scripts.yml@v2
    mode: merge

# Put anything additional you wish to have happen before running tests in an `install` section.
