# Branch whitelist
branches:
  only:
    - master
language: node_js
sudo: required
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - npm install -g bower web-component-tester@^6.0.0
  - npm install bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install
script:
  - xvfb-run npm test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
after_success:
- bin/tag_build.sh
